### ISSUE TITLE
Suggestion - Using Cologne as disinfectant

### ISSUE THREAD

**Issue by sick13** [DefbeatCZ/DefsLTS#13]
I don't know if this will be the scope of the mod so here is a suggestion
Add ability to use Cologne to disinfect bandages/ripped sheets
reason being right now only disinfectant can be used to do this
as a long term survival i think this would fit right in,also maybe boil ripped sheets with hot water and pot?

P.S
i tried the changes you made with the knives and cutting and all works as it should!

**Comment by DefbeatCZ** [comment]
- Adding recipe to sterilize bandages with cologne seems fine, but changing it into another wound disinfectant is bad idea as 1) There would be too much of it on map and 2) IRL, most of colognes are very toxic due to all the smells, preservatives and what not.

- Sterilization of clean rags with water is already possible in Vanilla. Make sure to boil the water first (in pot or pan).

**Comment by sick13** [comment]
ohh ok did not know about the vanilla option

**Comment by DefbeatCZ** [comment]
- Added new recipe to sterilize one rag with cologne (one to keep it on par with Whiskey and Alcohol)
- Wiki updated
